# Generated by Django 4.2.11 on 2024-04-12 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company_side", "0004_remove_company_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=20)),
                ("position", models.CharField(max_length=100)),
                ("picture", models.ImageField(blank=True, upload_to="employee\\img")),
                ("face_encoding", models.JSONField(blank=True, null=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_side.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Present"), ("0", "Absent")],
                        default="0",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
