# Generated by Django 4.2.11 on 2024-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_leave_leave_type_tax_salary_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary_employee",
            name="net_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salary_employee",
            name="total_deductions",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salary_employee",
            name="total_earnings",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
