# Generated by Django 4.2.11 on 2024-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_salary_employee_net_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sick_leave", "Sick Leave"),
                    ("vacation_leave", "Vacation Leave"),
                    ("casual_leave", "Casual Leave"),
                    ("earned_leave", "Earned Leave"),
                    ("maternity_leave", "Maternity Leave"),
                    ("paternity_leave", "Paternity Leave"),
                    ("bereavement_leave", "Bereavement Leave"),
                    ("compensatory_off", "Compensatory Off"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
