# Generated by Django 4.2.11 on 2024-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("1", "Company"), ("2", "Employee")], max_length=1
            ),
        ),
    ]
