# Generated by Django 4.2.11 on 2024-04-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("1", "Company"), ("2", "Employee")], max_length=50
            ),
        ),
    ]
