# Generated by Django 4.2.11 on 2024-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company_side", "0003_company_geo_f_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="company",
            name="location_range",
        ),
        migrations.RemoveField(
            model_name="company",
            name="longitude",
        ),
    ]
