# Generated by Django 4.2.11 on 2024-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_side", "0004_remove_company_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
